### ISSUE TITLE
Problem retraining from UI

### ISSUE THREAD

**Issue by Alfiegerner** [jakowenko/double-take#64]
Hi,

I have some faces wrongly allocated, I can select them in the UI, pick the correct person and select the tick to re-designate them, as per previous versions, but the logs appear to show no images are being selected for retraining, e.g. 3 images selected by this process, logs show 0:

```
info: testName: queuing 0 file(s) for training
info: testName: training complete in 3.81 sec
```
So all these images remain in my matched tab with incorrect names.

Not sure if relevant but also seeing lots of these in the logs:

```error: connect ECONNREFUSED 127.0.0.1:80```

**Comment by jakowenko** [comment]
Hey, this was a bug that was fixed yesterday. Make sure you're on v0.9.1 or the latest beta.

Let me know if that fixes your issue.

**Comment by Alfiegerner** [comment]
Thanks for quick response.

With .91 I can see the images going through for processing in there logs, e.g. queuing correct number selected, however when I return to the Match tab those images are still appearing. Should they be removed from that tab when processed?

**Comment by jakowenko** [comment]
I don't remove it from the match page anymore. When you train an image from the match page it copies that over to the training folder for that user.

**Comment by Alfiegerner** [comment]
Okay, understood thanks.

**Comment by Alfiegerner** [comment]
Can you confirm what deleting from the match tab does? Does it just clear from that view, no other function?

**Comment by jakowenko** [comment]
> Can you confirm what deleting from the match tab does? Does it just clear from that view, no other function?

It only removes that match result and image. It does not effect anything on the training side. That image would still remain since it's copied over.

**Comment by Alfiegerner** [comment]
That all makes sense, thanks.
